"""fix relationships

Revision ID: 3a772ad38b51
Revises: 87f57e57eef9
Create Date: 2025-03-16 06:03:51.160934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a772ad38b51'
down_revision: Union[str, None] = '87f57e57eef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'is_active')
    op.drop_column('managers', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('managers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
