"""add is_active column to avito_accounts

Revision ID: 3f669ace3552
Revises: de60f329ceb6
Create Date: 2025-03-22 18:01:43.374936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f669ace3552'
down_revision: Union[str, None] = 'de60f329ceb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avito_chats')
    op.add_column('avito_accounts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('avito_accounts', 'access_token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avito_accounts', 'access_token',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('avito_accounts', 'is_active')
    op.create_table('avito_chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('avito_chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('client_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['avito_accounts.id'], name='avito_chats_account_id_fkey'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name='avito_chats_manager_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='avito_chats_pkey'),
    sa.UniqueConstraint('avito_chat_id', name='avito_chats_avito_chat_id_key')
    )
    # ### end Alembic commands ###
