"""Create AvitoChat

Revision ID: 87f57e57eef9
Revises: 1d2e33f842d5
Create Date: 2025-03-16 05:43:59.658475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f57e57eef9'
down_revision: Union[str, None] = '1d2e33f842d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('avito_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('sender_contacts', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['avito_account_id'], ['avito_accounts.id'], name='messages_avito_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    # ### end Alembic commands ###
